version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - react-net

networks:
  react-net:
    driver: bridge
