version: '3'
services:
  frontend:
    build: .
    container_name: aas-frontend
    ports:
      - "80:80"
    depends_on:
      - db
      - pgadmin
      - web
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: aas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yourpassword
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: aas-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my_network

  web:
    image: aas-web
    container_name: aas-web
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
