version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
